#!/bin/bash

set -x
set -e

tar xfC libpam-runtime_all.tar.gz rfs ./usr/share/pam/common-account ./usr/share/pam/common-session ./usr/share/pam/common-password ./usr/share/pam/common-auth ./usr/share/pam/common-session-noninteractive

mv rfs/usr/share/pam rfs/etc/pam.d

sed -i rfs/etc/pam.d/common-account -e 's/^\$account_primary/account	[success=1 new_authtok_reqd=done default=ignore]	pam_unix.so/' -e 's/^\$account_additional//'
sed -i rfs/etc/pam.d/common-auth -e 's/^\$auth_primary/auth	[success=1 default=ignore]	pam_unix.so nullok_secure/' -e 's/^\$auth_additional//'
sed -i rfs/etc/pam.d/common-password -e 's/^\$password_primary/password	[success=1 default=ignore]	pam_unix.so obscure sha512/' -e 's/^\$password_additional//'
sed -i rfs/etc/pam.d/common-session -e 's/^\$session_primary/session	[default=1]			pam_permit.so/' -e 's/^\$session_additional/session	required	pam_unix.so\nsession	optional	pam_systemd.so/'
sed -i rfs/etc/pam.d/common-session-noninteractive -e 's/^\$session_nonint_primary/session	[default=1]			pam_permit.so/' -e 's/^\$session_nonint_additional/session	required	pam_unix.so/'
