ARG MAINTAINER
ARG SUPPORT

FROM ghcr.io/menucha-de/runtime:latest

LABEL maintainer="${MAINTAINER}"
LABEL support="${SUPPORT}"

ADD linux-image-rpi.tar.gz /
ADD linux-modules-rpi.tar.gz /

ADD rpi /
